<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Image extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Image_model');
    } 

    /*
     * Listing of image
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('image/index?');
        $config['total_rows'] = $this->Image_model->get_all_image_count();
        $this->pagination->initialize($config);

        $data['image'] = $this->Image_model->get_all_image($params);
        
        $data['_view'] = 'image/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new image
     */
    function add()
    {   
        
        $this->load->library('form_validation');
		    $this->form_validation->set_rules('travel_id','Travel Id','required|integer');
      
        
		
		if($this->form_validation->run())     
        {   
           
           $data = array();
           if(!empty($_FILES['files']['name'])){

          $filesCount = count($_FILES['files']['name']);
            for($i = 0; $i < $filesCount; $i++){
                $_FILES['file']['name']     = $_FILES['files']['name'][$i];
                $_FILES['file']['type']     = $_FILES['files']['type'][$i];
                $_FILES['file']['tmp_name'] = $_FILES['files']['tmp_name'][$i];
                $_FILES['file']['error']     = $_FILES['files']['error'][$i];
                $_FILES['file']['size']     = $_FILES['files']['size'][$i];
      
                $config['upload_path']   = './resources/img/travel/'; //Folder สำหรับ เก็บ ไฟล์ที่  Upload
                $config['allowed_types'] = 'gif|jpg|png|jpeg'; //รูปแบบไฟล์ที่ อนุญาตให้ Upload ได้
                $config['max_size']      = 0; //ขนาดไฟล์สูงสุดที่ Upload ได้ (กรณีไม่จำกัดขนาด กำหนดเป็น 0)
                $config['max_width']     = 0; //ขนาดความกว้างสูงสุด (กรณีไม่จำกัดขนาด กำหนดเป็น 0)
                $config['max_height']    = 0;  //ขนาดความสูงสูงสดุ (กรณีไม่จำกัดขนาด กำหนดเป็น 0)
                $rand = rand(1111,9999);
                $date= date("Y-m-d ");
                $config['file_name']  = $date.$rand;

 
        $this->load->library('upload', $config);
        $this->upload->initialize($config);

        if($this->upload->do_upload('file')){
                    // Uploaded file data
                    $fileData = $this->upload->data();
                    $uploadData[$i]['img'] = $fileData['file_name'];
                    $uploadData[$i]['travel_id'] = $this->input->post('travel_id');
                }
        else{
            show_error('The image you are trying to edit does not exist. The image file should be gif / jpg / png / jpeg. ');
        }
              }

              if(!empty($uploadData)){
    

                $image_id = $this->Image_model->add_image($uploadData);
                redirect('image/index');
              }
            }

        }

   
        else
        {
			$this->load->model('Travel_model');
			$data['all_travel'] = $this->Travel_model->get_all_travel();
            
            $data['_view'] = 'image/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a image
     */
    function edit($id)
    {   
        // check if the image exists before trying to edit it
        $data['image'] = $this->Image_model->get_image($id);

        $config['upload_path']   = './resources/img/travel/'; //Folder สำหรับ เก็บ ไฟล์ที่  Upload
        $config['allowed_types'] = 'gif|jpg|png|jpeg'; //รูปแบบไฟล์ที่ อนุญาตให้ Upload ได้
        $config['max_size']      = 0; //ขนาดไฟล์สูงสุดที่ Upload ได้ (กรณีไม่จำกัดขนาด กำหนดเป็น 0)
        $config['max_width']     = 0; //ขนาดความกว้างสูงสุด (กรณีไม่จำกัดขนาด กำหนดเป็น 0)
        $config['max_height']    = 0;  //ขนาดความสูงสูงสดุ (กรณีไม่จำกัดขนาด กำหนดเป็น 0)
        $rand = rand(1111,9999);
        $date= date("Y-m-d ");
        $config['file_name']  = $date.$rand;

 
        $this->load->library('upload', $config);

        
        if(isset($data['image']['id']))
        {
            $this->load->library('form_validation');

      $this->form_validation->set_rules('travel_id','Travel Id','required|integer');

      if($this->form_validation->run())     
            {   
              if ( ! $this->upload->do_upload('photo')) {
 
                show_error('The image you are trying to edit does not exist. The image file should be gif / jpg / png / jpeg.');
 
            }else { 
            $datax = $this->Image_model->delete_imagefiles($id);
            foreach($datax as $tx){
            $ssx = $tx['img'];
            }

           unlink('./resources/img/travel/'.$ssx);


            $data_upload= $this->upload->data();
            $fname=$data_upload['file_name'];

               $params = array(
              'travel_id' => $this->input->post('travel_id'),
              'img' => $fname,);           


            $this->Image_model->update_image($id,$params);            
                redirect('image/index'); 
         } 


             
            }
            else
            {
        $this->load->model('Travel_model');
        $data['all_travel'] = $this->Travel_model->get_all_travel();

                $data['_view'] = 'image/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The image you are trying to edit does not exist.');
    } 


    /*
     * Deleting image
     */
    function remove($id)
    {
        $data = $this->Image_model->delete_imagefiles($id);
       foreach($data as $t){
       $ss = $t['img'];
           }

           unlink('./resources/img/travel/'.$ss);

        
        $image = $this->Image_model->get_image($id);

        // check if the image exists before trying to delete it
        if(isset($image['id']))
        {
            $this->Image_model->delete_image($id);
            redirect('image/index');
        }
        else
            show_error('The image you are trying to delete does not exist.');
    }
    
}
