<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Travel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Travel_model');
    } 

    /*
     * Listing of travel
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('travel/index?');
        $config['total_rows'] = $this->Travel_model->get_all_travel_count();
        $this->pagination->initialize($config);

        $data['travel'] = $this->Travel_model->get_all_travel($params);
        
        $data['_view'] = 'travel/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new travel
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[255]');
		$this->form_validation->set_rules('type_id','Type Id','required|integer');
		$this->form_validation->set_rules('time','Time','required|max_length[255]');
		$this->form_validation->set_rules('tel','Tel','required|max_length[255]');
		$this->form_validation->set_rules('about','About','required');
		$this->form_validation->set_rules('address','Address','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'type_id' => $this->input->post('type_id'),
				'name' => $this->input->post('name'),
				'time' => $this->input->post('time'),
				'tel' => $this->input->post('tel'),
				'about' => $this->input->post('about'),
				'address' => $this->input->post('address'),
            );
            
            $travel_id = $this->Travel_model->add_travel($params);
            redirect('travel/index');
        }
        else
        {
			$this->load->model('Type_model');
			$data['all_type'] = $this->Type_model->get_all_type();
            
            $data['_view'] = 'travel/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a travel
     */
    function edit($id)
    {   
        // check if the travel exists before trying to edit it
        $data['travel'] = $this->Travel_model->get_travel($id);
        
        if(isset($data['travel']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required|max_length[255]');
			$this->form_validation->set_rules('type_id','Type Id','required|integer');
			$this->form_validation->set_rules('time','Time','required|max_length[255]');
			$this->form_validation->set_rules('tel','Tel','required|max_length[255]');
			$this->form_validation->set_rules('about','About','required');
			$this->form_validation->set_rules('address','Address','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'type_id' => $this->input->post('type_id'),
					'name' => $this->input->post('name'),
					'time' => $this->input->post('time'),
					'tel' => $this->input->post('tel'),
					'about' => $this->input->post('about'),
					'address' => $this->input->post('address'),
                );

                $this->Travel_model->update_travel($id,$params);            
                redirect('travel/index');
            }
            else
            {
				$this->load->model('Type_model');
				$data['all_type'] = $this->Type_model->get_all_type();

                $data['_view'] = 'travel/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The travel you are trying to edit does not exist.');
    } 

    /*
     * Deleting travel
     */
    function remove($id)
    {
        $ss2 = array();

        $data1 = $this->Travel_model->delete_imagefiles1($id);
        foreach($data1 as $t1){
        $name1 = $t1['id'];
           }

        
        
       

           $data2 = $this->Travel_model->delete_imagefiles2($name1);

            foreach($data2 as $t2){
            $ss2 = $t2['img'];
            unlink('./resources/img/travel/'.$ss2);
               }

        $travel = $this->Travel_model->get_travel($id);

        // check if the travel exists before trying to delete it
        if(isset($travel['id']))
        {
            $this->Travel_model->delete_travel($id);
            redirect('travel/index');
        }
        else
            show_error('The travel you are trying to delete does not exist.');
    }
    
}
