<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Type extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Type_model');
    } 

    /*
     * Listing of type
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('type/index?');
        $config['total_rows'] = $this->Type_model->get_all_type_count();
        $this->pagination->initialize($config);

        $data['type'] = $this->Type_model->get_all_type($params);
        
        $data['_view'] = 'type/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new type
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $type_id = $this->Type_model->add_type($params);
            redirect('type/index');
        }
        else
        {            
            $data['_view'] = 'type/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a type
     */
    function edit($id)
    {   
        // check if the type exists before trying to edit it
        $data['type'] = $this->Type_model->get_type($id);
        
        if(isset($data['type']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required|max_length[255]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Type_model->update_type($id,$params);            
                redirect('type/index');
            }
            else
            {
                $data['_view'] = 'type/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The type you are trying to edit does not exist.');
    } 

    /*
     * Deleting type
     */
    function remove($id)
    {
        $type = $this->Type_model->get_type($id);

        // check if the type exists before trying to delete it
        if(isset($type['id']))
        {
            $this->Type_model->delete_type($id);
            redirect('type/index');
        }
        else
            show_error('The type you are trying to delete does not exist.');
    }
    
}
