<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Travel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get travel by id
     */
    function get_travel($id)
    {
        return $this->db->get_where('travel',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all travel count
     */
    function get_all_travel_count()
    {
        $this->db->from('travel');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all travel
     */
    function get_all_travel($params = array())
    {
        $this->db->order_by('type_id', 'ASC');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('travel')->result_array();

    }
        
    /*
     * function to add new travel
     */
    function add_travel($params)
    {
        $this->db->insert('travel',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update travel
     */
    function update_travel($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('travel',$params);
    }
    
    function delete_imagefiles1($id)
    {
        $this->db->order_by('id', 'desc');
       
        return $this->db->get_where('travel',array('id'=>$id))->result_array();
        
    }

    function delete_imagefiles2($name1 = array())
    {
        $this->db->order_by('id', 'desc');
       if(isset($name1) && !empty($name1))
        {
           
        }
        return $this->db->get_where('image',array('travel_id'=>$name1))->result_array();
        
    }

    /*
     * function to delete travel
     */
    function delete_travel($id)
    {
         $this->db->delete('image',array('travel_id'=>$id));
        return $this->db->delete('travel',array('id'=>$id));

    }

}
