<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get type by id
     */
    function get_type($id)
    {
        return $this->db->get_where('type',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all type count
     */
    function get_all_type_count()
    {
        $this->db->from('type');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all type
     */
    function get_all_type($params = array())
    {
        $this->db->order_by('id', 'ASC');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('type')->result_array();
    }
        
    /*
     * function to add new type
     */
    function add_type($params)
    {
        $this->db->insert('type',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update type
     */
    function update_type($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('type',$params);
    }
    
    /*
     * function to delete type
     */
    function delete_type($id)
    {
        return $this->db->delete('type',array('id'=>$id));
    }
}
